version: "3.8"

services:
  backend:
    image: jjtechmaykon/my-backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  frontend:
    image: jjtechmaykon/my-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env

  mongo:
    image: jjtechmaykon/my-mongo
    ports:
      - "27017:27017"
    env_file:
      - ./database/.env
